### ISSUE TITLE
Results summary table 

### ISSUE THREAD

**Issue by peterk87** [peterk87/nf-flu#2]
Produce a basic 2 column table with sample name and results/comments. 

For example, for a fully sequenced AIV genome:

> All 8 segments were sequenced. Predicted subtype is H5N1. Top HA BLAST match is Influenza A virus (A/place/xx/2020) (NCBI accession). Top NA BLAST match is Influenza A virus (A/place/xx/2020) (NCBI accession).

or for a partially sequenced AIV genome:

> Only 7 segments were sequenced and assembled. The NA segment could not be assembled due to lack of reads (N=5). Predicted subtype was H5 with undetermined N subtype. Top HA BLAST match is Influenza A virus (A/place/xx/2020) (NCBI accession).

### TODO

- [ ] handle multiple cases of various gene segments missing or low coverage
- [ ] mixed sample reporting
- [ ] report depth and breadth of coverage of segments below thresholds
